cr_homepage:
    path:     /
    defaults: { _controller: CRBundle:Default:index }

cr_terrain:
    path: /terrain
    defaults: { _controller: CRBundle:Terrain:Terrain }

cr_presentation:
    path: /presentation
    defaults: { _controller: CRBundle:Presentation:Presentation }
