cr_homepage:
    path:     /
    defaults: { _controller: CRBundle:Default:index }

cr_terrain:
    path: /terrain
    defaults: { _controller: CRBundle:Terrain:Terrain }

cr_presentation:
    path: /presentation
    defaults: { _controller: CRBundle:Presentation:Presentation }

cr_replay:
    path: /replay
    defaults: { _controller: CRBundle:Replay:Replay }

cr_search:
    path: /recherche
    defaults: { _controller: CRBundle:Search:Search }
